name: workflow_dispatch 테스트

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      isBoolean:
        type: boolean
        description: 'workflow_dispatch Boolean'
        required: false
      isStockSyncMocking:
        type: boolean
        description: '재고연동 가상화 여부'
        required: false
        default: false
        

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: catalogyo/fe-api
          STOCK_SYNC_MOCKING: ${{ github.event.inputs.isStockSyncMocking }}
        run: |
          echo ${{ github.event.inputs.isBoolean }}
          echo "STOCK_SYNC_MOCKING ${STOCK_SYNC_MOCKING:-false}"
  
